### ISSUE TITLE
html code shows in success message 

### ISSUE THREAD

**Issue by LoreDirick** [datacamp/courses-intro-to-python#10]
In the second exercise of chapter 3 (https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-3-functions-and-packages?ex=2), the success message turns out like this:
https://www.dropbox.com/s/ivqtnrdu2t43afr/Screenshot%202017-01-05%2016.02.24.png?dl=0

**Comment by machow** [comment]
hmm.. I see the same thing on campus prod, but tried the same `success_msg` sct in a new exercise the teach editor and it worked okay.

![image](https://cloud.githubusercontent.com/assets/2574498/21700077/8364ceda-d36c-11e6-9381-6aec132b4694.png)

SCT: 

```
success_msg("Great job! The [`len()`](https://docs.python.org/3/library/functions.html#len) function is extremely useful: it also works on strings to count the number of characters!")
```

**Comment by filipsch** [comment]
@machow was the teach editor exercise you were experimenting with using the package management system?

**Comment by machow** [comment]
@filipsch yeah. I wonder where the fix was, though--pythonbackend?

**Comment by hugobowne** [comment]
we're good! 

<img width="612" alt="screenshot 2017-01-10 15 09 15" src="https://cloud.githubusercontent.com/assets/4182382/21822827/d032b7b2-d746-11e6-89a8-c0027a6ca46f.png">

Closing.

**Comment by filipsch** [comment]
@machow must've been something funky with package version of markdown2 or something, I guess. Problem autosolved ¯\_(ツ)_/¯
