### ISSUE TITLE
Warnings without explanation should be removed or turned into forward references

### ISSUE THREAD

**Issue by gvwilson** [datacamp/courses-intro-to-python#34]
Chapter 2 says:

> Watch out! `list()` and `[:]` might not copy properly if you put complex things in your lists.

Without an explanation of what "complex things" are, or why this might not work, or a forward reference to such explanations, all we've done is scare learners without informing them.

**Comment by karawoo** [comment]
I'm going through this course and made a note of this as well. We could at least give an example of the type of thing that wouldn't work.
