### ISSUE TITLE
learnpython.org: Classes_and_Objects static var represented as instance var

### ISSUE THREAD

**Issue by dz0** [datacamp/courses-intro-to-python#50]
Hi, not sure if I should address the issue here, but maybe you can redirect :)

in https://www.learnpython.org/en/Classes_and_Objects
in Accessing Object Variables
in 3-rd exercise

```python
class MyClass:
    variable = "blah"

    def function(self):
        print("This is a message inside the class.")

myobjectx = MyClass()
myobjecty = MyClass()

myobjecty.variable = "yackity"

# Then pring out both values
print(myobjectx.variable)
print(myobjecty.variable)
```

explanation does'nt mention, that new instance variable is created (and overrides static variable for that instance)
And doesn't mention possibility of  ```MyClass.variable = "asdf"```

imo, instead  should  be introduced 
```python
    __init__(self):
         self.variable = "blah"
```

**Comment by westonstearns** [comment]
@yashasroy support@learnpython.org

**Comment by yashasroy** [comment]
@dz0 All learnpython.org related issues can be addressed to support@learnpython.org. As this repository pertains to DataCamp's Intro to Python for Data Science course, I'm closing this. If you come across any issues in DataCamp courses, please feel free to report it to us via the 'Report an Issue' button (as shown below), and we'll look into it. Thanks! :)

![screenshot 2017-09-27 23 26 11](https://user-images.githubusercontent.com/20912644/30948049-59c0d8a4-a3db-11e7-971a-ea4d3bd8b7a5.png)
