### ISSUE TITLE
typo in string methods exercise

### ISSUE THREAD

**Issue by machow** [datacamp/courses-intro-to-python#53]
It looks like there is an extra `========` in the explanation text

https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-3-functions-and-packages?ex=6

![image](https://user-images.githubusercontent.com/2574498/32562929-e1940e8c-c47d-11e7-8845-5b5d5047f920.png)

**Comment by yashasroy** [comment]
Thanks - fixed in #57.
