### ISSUE TITLE
Chap 2 - Session Keeps Timing Out

### ISSUE THREAD

**Issue by MelRemy** [datacamp/courses-intro-to-python#67]
**Background**
"Hi, for some reason in Python class after I listened to the next session I’m able to run code but the submit answer seems to fail. Restart allows to run code again but I can’t submit the answer."

**Replicate**

I can confirm when inputting the accurate code to exercise: 
https://campus.datacamp.com/courses/intro-to-python-for-data-science/chapter-2-python-lists?ex=2

The system accepts the code, lets me know I've passed but when I check the outline of the course it resets back to looking as if I never submitted an answer for that exercise:

![screen shot 2018-08-09 at 11 32 33 am](https://user-images.githubusercontent.com/38881425/43909312-0a157d74-9bc8-11e8-8aaa-045906f0f9c6.png)

![screen shot 2018-08-09 at 11 32 54 am](https://user-images.githubusercontent.com/38881425/43909318-0ded8ab8-9bc8-11e8-83be-574fd259f1d2.png)

UID: 2692990
<div style="background-color:#BBDEFB;padding:10px;border-radius:5px;" id="zdArea">                             	                                                              <div style="text-decoration:underline;margin-bottom:5px;color:#00000082;" id="zd-ReservedAreaHeader">                 <span class="zdDescription" style="font-weight: bold;"><h3 style="margin:0px;padding:0px;">Zendesk Information</h3></span>                 <div class="zdValue"></div>             </div>                          <div class="ValueTypeField" style id="zd-TicketLinkUpdateIssue"><span style="margin-right:5px;">&#9679;</span>                 <span class="zdDescription" style="font-weight: bold;">Linked with zendesk ticket:</span>                 <span class="zdValue"><a href="https://datacamp.zendesk.com/agent/tickets/109989" target="_blank">109989</a></span>             </div>             </div>

**Comment by MelRemy** [comment]
@richierocks

**Comment by klmedeiros** [comment]
This is a product problem @ncarchedi

**Comment by richierocks** [comment]
I can't reproduce this; the exercise works correctly for me.

**Comment by ncarchedi** [comment]
The solution works for me as well. Feel free to close.

**Comment by MelRemy** [comment]
@ncarchedi Hey, this is a similar situation as https://github.com/datacamp/courses-importing-data-in-python-I/issues/24

I'm not sure if this User specific?
